apiVersion: v1
kind: Service
metadata:
  name: orderentry
  labels:
    app: orderentry
spec:
  ports:
    - name: grpc-web
      port: 9085
  selector:
    app: orderentry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderentry
  labels:
    app: orderentry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderentry
  template:
    metadata:
      labels:
        app: orderentry
    spec:
      containers:
        - name: orderentry
          image: us.gcr.io/secwager/orderentry:dev
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: gcloud-secret
                  key:  firebase-adminsdk-key
            - name: POD_NAME_WITH_ORDINAL
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: secwager-kafka-bootstrap:9092
          imagePullPolicy: Always
          ports:
            - containerPort: 9085
