apiVersion: v1
kind: Service
metadata:
  name: marketdata
  labels:
    app: marketdata
spec:
  ports:
    - name: grpc-web
      port: 9300
  selector:
    app: marketdata
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: marketdata
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: marketdata
    spec:
      containers:
        - name: marketdata
          image: us.gcr.io/secwager/marketdata:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 9300