apiVersion: v1
kind: Service
metadata:
  name: cashier
  labels:
    app: cashier
spec:
  ports:
    - name: grpc
      port: 9090
  selector:
    app: cashier
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cashier
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cashier
    spec:
      containers:
        - name: cashier
          image: us.gcr.io/secwager/cashier:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 9090