java_library(
    name = "grpc-server",
    srcs = ["src/main/java/com/secwager/common/GrpcServer.java"],
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:io_grpc_grpc_api",
        "@maven//:io_grpc_grpc_netty_shaded",
    ],
)
