proto_library(
    name = "matchengine_proto",
    srcs = ["market.proto"],
    visibility = ["//visibility:public"],
)

cc_proto_library(
    name = "matchengine_cc_proto",
    visibility = ["//visibility:public"],
    deps = [":matchengine_proto"],
)
