apiVersion: v1
kind: Service
metadata:
  name: orderentry
  labels:
    app: orderentry
spec:
  ports:
    - name: grpc-web
      port: 9085
  selector:
    app: orderentry
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orderentry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: orderentry
    spec:
      containers:
        - name: orderentry
          image: us.gcr.io/secwager/orderentry:dev
          env:
            - name: POD_NAME_WITH_ORDINAL
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: secwager-kafka-bootstrap:9092
          imagePullPolicy: Always
          ports:
            - containerPort: 9085