apiVersion: v1
kind: Service
metadata:
  name: orderentry
  labels:
    app: orderentry
spec:
  ports:
    - port: 9085
      name: grpc-web-port
  clusterIP: None
  selector:
    app: orderentry
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: orderentry
spec:
  serviceName: "orderentry"
  replicas: 1
  selector:
    matchLabels:
      app: orderentry
  template:
    metadata:
      labels:
        app: orderentry
    spec:
      containers:
        - name: orderentry
          image: us.gcr.io/secwager/orderentry:dev
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: secwager-kafka-bootstrap