apiVersion: v1
kind: Service
metadata:
  name: cashier
  labels:
    app: cashier
spec:
  ports:
    - name: grpc
      port: 9305
  selector:
    app: cashier
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cashier
  labels:
    app: cashier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cashier
  template:
    metadata:
      labels:
        app: cashier
    spec:
      containers:
        - name: cashier
          image: us.gcr.io/secwager/cashier:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 9305