apiVersion: v1
kind: Service
metadata:
  name: matchengine
  labels:
    app: matchengine
spec:
  clusterIP: None
  selector:
    app: matchengine
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: matchengine
spec:
  serviceName: "matchengine"
  replicas: 2
  selector:
    matchLabels:
      app: matchengine
  template:
    metadata:
      labels:
        app: matchengine
    spec:
      containers:
        - name: matchengine
          image: us.gcr.io/secwager/matchengine:dev
          env:
            - name: POD_NAME_WITH_ORDINAL
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: secwager-kafka-bootstrap