apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: secwager-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: secwager-ui
spec:
  hosts:
  - "secwager.com"
  gateways:
  - secwager-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: secwager-ui
        port:
          number: 9080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: marketdata
spec:
  hosts:
    - "marketdata"
  gateways:
    - secwager-gateway
  http:
    - match:
        - port: 80
      route:
        - destination:
            host: marketdata
            port:
              number: 9300
      corsPolicy:
        allowOrigin:
          - "*"
        allowMethods:
          - POST
          - GET
          - OPTIONS
          - PUT
          - DELETE
        allowHeaders:
          - grpc-timeout
          - content-type
          - keep-alive
          - user-agent
          - cache-control
          - content-type
          - content-transfer-encoding
          - custom-header-1
          - x-accept-content-transfer-encoding
          - x-accept-response-streaming
          - x-user-agent
          - x-grpc-web
        maxAge: 1728s
        exposeHeaders:
          - custom-header-1
          - grpc-status
          - grpc-message
        allowCredentials: true
