apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: secwager
spec:
  kafka:
    version: 2.3.0
    replicas: 1
    listeners:
      plain: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: order-inbound
  labels:
    strimzi.io/cluster: secwager
spec:
  partitions: 2
  replicas: 1
  config:
    retention.ms: 30000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: order-status-events
  labels:
    strimzi.io/cluster: secwager
spec:
  partitions: 2
  replicas: 1
  config:
    retention.ms: 30000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: market-data-depth
  labels:
    strimzi.io/cluster: secwager
spec:
  partitions: 2
  replicas: 1
  config:
    retention.ms: 30000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: market-data-matched-trades
  labels:
    strimzi.io/cluster: secwager
spec:
  partitions: 2
  replicas: 1
  config:
    retention.ms: 30000
    segment.bytes: 1073741824